/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentmanagement;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ishika Gupta
 */
public class attendance extends javax.swing.JFrame {
 Connection conn;
PreparedStatement pst;
ResultSet rs;
DefaultTableModel d;
    
    /**
     * Creates new form attendance
     */
    public attendance() {
        initComponents();
        connect();
        Attendance_Load();
        Dimension dim= Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2,dim.height/2-this.getSize().height/2);
        this.setBackground(new Color(0,0,0,0));
        jPanel1.setBackground(new Color(0,0,0,0));
        roll.setBackground(new Color(0,0,0,0));
        stid.setBackground(new Color(0,0,0,0));
        stname.setBackground(new Color(0,0,0,0));
        txtdate.setBackground(new Color(0,0,0,0));
        attend.setBackground(new Color(0,0,0,0));   
        
    }
    
    public void connect(){
     try {
         Class.forName("com.mysql.cj.jdbc.Driver");
         conn= DriverManager.getConnection("jdbc:mysql://localhost/schoolmanagementsystem","root","");
         
         
     } catch (ClassNotFoundException ex) {
         Logger.getLogger(attendance.class.getName()).log(Level.SEVERE, null, ex);
     } catch (SQLException ex) {
         Logger.getLogger(attendance.class.getName()).log(Level.SEVERE, null, ex);
     }
    }
    
     public void Attendance_Load(){
        
        int c;
       
     try {
         pst= conn.prepareStatement("select * from attendance");
         
              rs= pst.executeQuery();
     
        ResultSetMetaData rsd= rs.getMetaData();
        c= rsd.getColumnCount();
        
          d = (DefaultTableModel)attendancetable.getModel();
        d.setRowCount(0);
        
        while(rs.next()){
            Vector v2= new Vector();
            for(int i=1;i<=c;i++){
                
                v2.add(rs.getString("Studentid"));
                v2.add(rs.getString("rollno"));
                v2.add(rs.getString("name"));
                v2.add(rs.getString("date"));
                v2.add(rs.getString("attendance"));
             
            }
            d.addRow(v2);
            
        }
     } catch (SQLException ex) {
         Logger.getLogger(attendance.class.getName()).log(Level.SEVERE, null, ex);
     }
        
        
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        attendancetable = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        stname = new javax.swing.JTextField();
        txtdate = new javax.swing.JTextField();
        attend = new javax.swing.JTextField();
        jlabel5 = new javax.swing.JLabel();
        jlabel4 = new javax.swing.JLabel();
        jlabel3 = new javax.swing.JLabel();
        jlabel2 = new javax.swing.JLabel();
        roll = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        stid = new javax.swing.JTextField();
        jlabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        attendancetable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Student ID", "Roll  No.", "Student Name", "Date", "Attendance"
            }
        ));
        jScrollPane1.setViewportView(attendancetable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 490, 380));

        jButton2.setBackground(new java.awt.Color(51, 240, 0));
        jButton2.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 660, -1, -1));

        jButton1.setBackground(new java.awt.Color(51, 240, 0));
        jButton1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 660, -1, -1));

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 240, 30));

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 610, 240, 30));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 240, 30));

        stname.setBackground(new java.awt.Color(204, 204, 204));
        stname.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        stname.setForeground(new java.awt.Color(255, 255, 255));
        stname.setText("Enter Student name");
        stname.setBorder(null);
        stname.setOpaque(false);
        stname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                stnameFocusGained(evt);
            }
        });
        stname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stnameActionPerformed(evt);
            }
        });
        jPanel1.add(stname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 240, 40));

        txtdate.setBackground(new java.awt.Color(204, 204, 204));
        txtdate.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        txtdate.setForeground(new java.awt.Color(255, 255, 255));
        txtdate.setText("Enter date");
        txtdate.setBorder(null);
        txtdate.setOpaque(false);
        txtdate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtdateFocusGained(evt);
            }
        });
        txtdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdateActionPerformed(evt);
            }
        });
        jPanel1.add(txtdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 240, 40));

        attend.setBackground(new java.awt.Color(204, 204, 204));
        attend.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        attend.setForeground(new java.awt.Color(255, 255, 255));
        attend.setText("Enter attendance");
        attend.setBorder(null);
        attend.setOpaque(false);
        attend.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                attendFocusGained(evt);
            }
        });
        attend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attendActionPerformed(evt);
            }
        });
        jPanel1.add(attend, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 240, 40));

        jlabel5.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jlabel5.setForeground(new java.awt.Color(51, 204, 0));
        jlabel5.setText("Student Name");
        jPanel1.add(jlabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 240, 30));

        jlabel4.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jlabel4.setForeground(new java.awt.Color(51, 204, 0));
        jlabel4.setText("Date");
        jPanel1.add(jlabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 240, 30));

        jlabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jlabel3.setForeground(new java.awt.Color(51, 204, 0));
        jlabel3.setText("Attendance");
        jPanel1.add(jlabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 240, 30));

        jlabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jlabel2.setForeground(new java.awt.Color(51, 204, 0));
        jlabel2.setText("Roll No.");
        jPanel1.add(jlabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 240, 30));

        roll.setBackground(new java.awt.Color(204, 204, 204));
        roll.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        roll.setForeground(new java.awt.Color(255, 255, 255));
        roll.setText("Enter Roll No.");
        roll.setBorder(null);
        roll.setOpaque(false);
        roll.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rollFocusGained(evt);
            }
        });
        roll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rollActionPerformed(evt);
            }
        });
        jPanel1.add(roll, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 240, 40));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 240, 30));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 240, 30));

        stid.setBackground(new java.awt.Color(204, 204, 204));
        stid.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        stid.setForeground(new java.awt.Color(255, 255, 255));
        stid.setText("Enter Student ID");
        stid.setBorder(null);
        stid.setOpaque(false);
        stid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                stidFocusGained(evt);
            }
        });
        stid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stidActionPerformed(evt);
            }
        });
        jPanel1.add(stid, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 240, 40));

        jlabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jlabel1.setForeground(new java.awt.Color(51, 204, 0));
        jlabel1.setText("Student ID");
        jPanel1.add(jlabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 240, 30));

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\aksha\\Downloads\\iconfinder_Auditorium_classroom_pupil_school_students__4763272.png")); // NOI18N
        jLabel3.setText(" Attendance");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 300, 70));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\aksha\\Desktop\\blue.jpg")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 860, 610));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\aksha\\Desktop\\green.jpg")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 100));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stidFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_stidFocusGained
        stid.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_stidFocusGained

    private void stidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stidActionPerformed
       
// TODO add your handling code here:
    }//GEN-LAST:event_stidActionPerformed

    private void rollFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rollFocusGained
        roll.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_rollFocusGained

    private void rollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rollActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rollActionPerformed

    private void attendFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_attendFocusGained
         attend.setText("");
// TODO add your handling code here:
    }//GEN-LAST:event_attendFocusGained

    private void attendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_attendActionPerformed

    private void txtdateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtdateFocusGained
         txtdate.setText("");
// TODO add your handling code here:
    }//GEN-LAST:event_txtdateFocusGained

    private void txtdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdateActionPerformed

    private void stnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_stnameFocusGained
         stname.setText("");
// TODO add your handling code here:
    }//GEN-LAST:event_stnameFocusGained

    private void stnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stnameActionPerformed
        stname.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_stnameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        String rollno = roll.getText();
        String Studentid = stid.getText();
        String name = stname.getText();
        String date = txtdate.getText();
        String attendance  = attend.getText();
        
     try {
         pst= conn.prepareStatement("insert into attendance (rollno,Studentid,name,date,attendance)values(?,?,?,?,?)");
         pst.setString(1,rollno);
                pst.setString(2,Studentid);
                pst.setString(3,name);
                pst.setString(4,date);
                pst.setString(5,attendance);
                pst.executeUpdate();
                
                JOptionPane.showMessageDialog(null,"Attendance added ");
                roll.setText("");
                stid.setText("");
                stname.setText("");
               
                txtdate.setText("");
                attend.setText("");
               
                roll.requestFocus();
                
        
     } catch (SQLException ex) {
         Logger.getLogger(attendance.class.getName()).log(Level.SEVERE, null, ex);
     }
               
    
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       setVisible(false);
        AdminDashboard ad= new AdminDashboard();
        ad.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(attendance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new attendance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField attend;
    private javax.swing.JTable attendancetable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel jlabel1;
    private javax.swing.JLabel jlabel2;
    private javax.swing.JLabel jlabel3;
    private javax.swing.JLabel jlabel4;
    private javax.swing.JLabel jlabel5;
    private javax.swing.JTextField roll;
    private javax.swing.JTextField stid;
    private javax.swing.JTextField stname;
    private javax.swing.JTextField txtdate;
    // End of variables declaration//GEN-END:variables
}
