/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentmanagement;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Ishika Gupta
 */
public class department extends javax.swing.JFrame {
Connection conn;
PreparedStatement pst;
ResultSet rs;
    /**
     * Creates new form department
     */
    public department() {
        initComponents();
        
        connect();
        
        Dimension dim= Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2,dim.height/2-this.getSize().height/2);
        this.setBackground(new Color(0,0,0,0));
        jPanel1.setBackground(new Color(0,0,0,0));
        txtstudentid.setBackground(new Color(0,0,0,0));
        txtdepartid.setBackground(new Color(0,0,0,0));
        txtdepartname.setBackground(new Color(0,0,0,0));
        txtbranch.setBackground(new Color(0,0,0,0));
        txtsem.setBackground(new Color(0,0,0,0));
    }
    
    
    
    public void connect(){
        
    try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        conn= DriverManager.getConnection("jdbc:mysql://localhost/schoolmanagementsystem","root","");
        
        
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(department.class.getName()).log(Level.SEVERE, null, ex);
    } catch (SQLException ex) {
        Logger.getLogger(department.class.getName()).log(Level.SEVERE, null, ex);
    }
          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txtsem = new javax.swing.JComboBox<>();
        jSeparator5 = new javax.swing.JSeparator();
        jlabel5 = new javax.swing.JLabel();
        jlabel4 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        txtbranch = new javax.swing.JTextField();
        txtdepartname = new javax.swing.JComboBox<>();
        jSeparator3 = new javax.swing.JSeparator();
        jlabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jlabel2 = new javax.swing.JLabel();
        txtdepartid = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txtstudentid = new javax.swing.JTextField();
        jlabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(51, 240, 0));
        jButton2.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 660, -1, -1));

        jButton1.setBackground(new java.awt.Color(51, 240, 0));
        jButton1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 660, -1, -1));

        txtsem.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        txtsem.setForeground(new java.awt.Color(255, 255, 255));
        txtsem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SEM 1", "SEM 2", "SEM 3", "SEM 4", "SEM 5", "SEM 6", "SEM 7", "SEM 8" }));
        txtsem.setBorder(null);
        txtsem.setOpaque(false);
        txtsem.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtsemFocusGained(evt);
            }
        });
        jPanel1.add(txtsem, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, 240, 30));

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 610, 240, 30));

        jlabel5.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jlabel5.setForeground(new java.awt.Color(51, 204, 0));
        jlabel5.setText("Semester");
        jPanel1.add(jlabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 240, 30));

        jlabel4.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jlabel4.setForeground(new java.awt.Color(51, 204, 0));
        jlabel4.setText("Branch");
        jPanel1.add(jlabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 240, 30));

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 240, 30));

        txtbranch.setBackground(new java.awt.Color(204, 204, 204));
        txtbranch.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        txtbranch.setForeground(new java.awt.Color(255, 255, 255));
        txtbranch.setText("Enter Branch");
        txtbranch.setBorder(null);
        txtbranch.setOpaque(false);
        txtbranch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtbranchFocusGained(evt);
            }
        });
        txtbranch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbranchActionPerformed(evt);
            }
        });
        jPanel1.add(txtbranch, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 240, 40));

        txtdepartname.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        txtdepartname.setForeground(new java.awt.Color(255, 255, 255));
        txtdepartname.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IET Department", "Management Department", "Design Department" }));
        txtdepartname.setBorder(null);
        txtdepartname.setOpaque(false);
        txtdepartname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtdepartnameFocusGained(evt);
            }
        });
        txtdepartname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdepartnameActionPerformed(evt);
            }
        });
        jPanel1.add(txtdepartname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 240, 30));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 240, 30));

        jlabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jlabel3.setForeground(new java.awt.Color(51, 204, 0));
        jlabel3.setText("Department Name");
        jPanel1.add(jlabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 240, 30));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 240, 30));

        jlabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jlabel2.setForeground(new java.awt.Color(51, 204, 0));
        jlabel2.setText("Department ID");
        jPanel1.add(jlabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 240, 30));

        txtdepartid.setBackground(new java.awt.Color(204, 204, 204));
        txtdepartid.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        txtdepartid.setForeground(new java.awt.Color(255, 255, 255));
        txtdepartid.setText("Enter Department ID");
        txtdepartid.setBorder(null);
        txtdepartid.setOpaque(false);
        txtdepartid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtdepartidFocusGained(evt);
            }
        });
        txtdepartid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdepartidActionPerformed(evt);
            }
        });
        jPanel1.add(txtdepartid, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 240, 40));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 240, 30));

        txtstudentid.setBackground(new java.awt.Color(204, 204, 204));
        txtstudentid.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        txtstudentid.setForeground(new java.awt.Color(255, 255, 255));
        txtstudentid.setText("Enter Student ID");
        txtstudentid.setBorder(null);
        txtstudentid.setOpaque(false);
        txtstudentid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtstudentidFocusGained(evt);
            }
        });
        txtstudentid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstudentidActionPerformed(evt);
            }
        });
        jPanel1.add(txtstudentid, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 240, 40));

        jlabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jlabel1.setForeground(new java.awt.Color(51, 204, 0));
        jlabel1.setText("Student ID");
        jPanel1.add(jlabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 240, 30));

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\aksha\\Downloads\\iconfinder_binary-tree_49580.png")); // NOI18N
        jLabel3.setText("Department");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 280, 80));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\aksha\\Desktop\\blue.jpg")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 490, 610));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\aksha\\Desktop\\green.jpg")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 110));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 110, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 110));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 721, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtstudentidFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtstudentidFocusGained
        txtstudentid.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstudentidFocusGained

    private void txtstudentidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstudentidActionPerformed
          
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstudentidActionPerformed

    private void txtdepartidFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtdepartidFocusGained
        txtdepartid.setText("");
// TODO add your handling code here:
    }//GEN-LAST:event_txtdepartidFocusGained

    private void txtdepartidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdepartidActionPerformed
      
// TODO add your handling code here:
    }//GEN-LAST:event_txtdepartidActionPerformed

    private void txtbranchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtbranchFocusGained
       txtbranch.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbranchFocusGained

    private void txtbranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbranchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbranchActionPerformed

    private void txtdepartnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtdepartnameFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_txtdepartnameFocusGained

    private void txtsemFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtsemFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_txtsemFocusGained

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String studentid = txtstudentid.getText();
        String departmentid = txtdepartid.getText();
        String departmentname = txtdepartname.getSelectedItem().toString();
        String branch = txtbranch.getText();
        String semester = txtsem.getSelectedItem().toString();
        
    try {
          pst= conn.prepareStatement("insert into department(studentid,departmentid,departmentname,branch,semester)values(?,?,?,?,?)");
          pst.setString(1,studentid);
          pst.setString(2,departmentid);
          pst.setString(3,departmentname);
          pst.setString(4,branch);
          pst.setString(5,semester);
          pst.executeUpdate();
                
          JOptionPane.showMessageDialog(null,"Student added in department");
          txtstudentid.setText("");
          txtdepartid.setText("");
          txtdepartname.setSelectedIndex(-1);
          txtbranch.setText("");
          txtsem.setSelectedIndex(-1);       
          txtstudentid.requestFocus();
                
                
    } catch (SQLException ex) {
        Logger.getLogger(department.class.getName()).log(Level.SEVERE, null, ex);
    }
                


// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtdepartnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdepartnameActionPerformed
        
// TODO add your handling code here:
    }//GEN-LAST:event_txtdepartnameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
        AdminDashboard ad= new AdminDashboard();
        ad.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(department.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(department.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(department.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(department.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
       new department().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel jlabel1;
    private javax.swing.JLabel jlabel2;
    private javax.swing.JLabel jlabel3;
    private javax.swing.JLabel jlabel4;
    private javax.swing.JLabel jlabel5;
    private javax.swing.JTextField txtbranch;
    private javax.swing.JTextField txtdepartid;
    private javax.swing.JComboBox<String> txtdepartname;
    private javax.swing.JComboBox<String> txtsem;
    private javax.swing.JTextField txtstudentid;
    // End of variables declaration//GEN-END:variables
}
