/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentmanagement;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ishika Gupta
 */


public class Exam extends javax.swing.JFrame {

    /**
     * Creates new form Exam
     */
     Connection conn;
PreparedStatement pst;
ResultSet rs;
DefaultTableModel d;





    public Exam() {
        initComponents();
        connect();
        Exam_Load();
        
        Dimension dim= Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2,dim.height/2-this.getSize().height/2);
        this.setBackground(new Color(0,0,0,0));
        jPanel1.setBackground(new Color(0,0,0,0));
        txtexamid.setBackground(new Color(0,0,0,0));
        txtsubject.setBackground(new Color(0,0,0,0));
        txtexamdate.setBackground(new Color(0,0,0,0));
        txtexamtime.setBackground(new Color(0,0,0,0));
        txtsemester.setBackground(new Color(0,0,0,0));   
        txtdepartment.setBackground(new Color(0,0,0,0));
        
    }
        
        
        public void connect(){
    
         try {
             Class.forName("com.mysql.cj.jdbc.Driver");
             conn= DriverManager.getConnection("jdbc:mysql://localhost/schoolmanagementsystem","root","");
             
             
             
             
             
             
             
         } catch (ClassNotFoundException ex) {
             Logger.getLogger(Exam.class.getName()).log(Level.SEVERE, null, ex);
         } catch (SQLException ex) {
             Logger.getLogger(Exam.class.getName()).log(Level.SEVERE, null, ex);
         }
            
}
     public void Exam_Load(){
        
        int c;
        try {
            pst= conn.prepareStatement("select * from exam");
              rs= pst.executeQuery();
     
        ResultSetMetaData rsd= rs.getMetaData();
        c= rsd.getColumnCount();
        
        d= (DefaultTableModel)examtable.getModel();
        d.setRowCount(0);
        
        while(rs.next()){
            Vector v2= new Vector();
            for(int i=1;i<=c;i++){
                
                v2.add(rs.getString("examid"));
                v2.add(rs.getString("courseid"));
                v2.add(rs.getString("examdate"));
                v2.add(rs.getString("examtime"));
                v2.add(rs.getString("semester"));
                v2.add(rs.getString("department"));
            }
            d.addRow(v2);
            
        }
        
        
        
        
        } catch (SQLException ex) {
            Logger.getLogger(AdminHomePage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator6 = new javax.swing.JSeparator();
        txtdepartment = new javax.swing.JComboBox<>();
        jlcomboBox1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        examtable = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txtsemester = new javax.swing.JComboBox<>();
        jSeparator5 = new javax.swing.JSeparator();
        jlcomboBox = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        txtexamtime = new javax.swing.JTextField();
        jlabel4 = new javax.swing.JLabel();
        jlabel3 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txtexamdate = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        txtsubject = new javax.swing.JTextField();
        jlabel2 = new javax.swing.JLabel();
        txtexamid = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jlabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 690, 240, 20));

        txtdepartment.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        txtdepartment.setForeground(new java.awt.Color(255, 255, 255));
        txtdepartment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "B.TECH", "M.TECH", "BBA", "MBA", " " }));
        txtdepartment.setBorder(null);
        txtdepartment.setOpaque(false);
        jPanel1.add(txtdepartment, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 650, 240, 30));

        jlcomboBox1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jlcomboBox1.setForeground(new java.awt.Color(51, 204, 0));
        jlcomboBox1.setText("Department");
        jPanel1.add(jlcomboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 620, 240, 30));

        examtable.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        examtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Exam ID", "Course", "Exam Date", "Exam Time", "Semester", "Department"
            }
        ));
        jScrollPane1.setViewportView(examtable);
        if (examtable.getColumnModel().getColumnCount() > 0) {
            examtable.getColumnModel().getColumn(0).setResizable(false);
            examtable.getColumnModel().getColumn(1).setResizable(false);
            examtable.getColumnModel().getColumn(2).setResizable(false);
            examtable.getColumnModel().getColumn(3).setResizable(false);
            examtable.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 490, 380));

        jButton2.setBackground(new java.awt.Color(51, 204, 0));
        jButton2.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 740, 90, 30));

        jButton1.setBackground(new java.awt.Color(51, 204, 0));
        jButton1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 740, 90, 30));

        txtsemester.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        txtsemester.setForeground(new java.awt.Color(255, 255, 255));
        txtsemester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SEM 1", "SEM 2", "SEM 3", "SEM 4", "SEM 5", "SEM 6", "SEM 7", "SEM 8" }));
        txtsemester.setBorder(null);
        txtsemester.setOpaque(false);
        txtsemester.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtsemesterFocusGained(evt);
            }
        });
        jPanel1.add(txtsemester, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 240, 30));

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 600, 240, 20));

        jlcomboBox.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jlcomboBox.setForeground(new java.awt.Color(51, 204, 0));
        jlcomboBox.setText("Semester");
        jPanel1.add(jlcomboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 240, 30));

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 240, -1));

        txtexamtime.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        txtexamtime.setForeground(new java.awt.Color(255, 255, 255));
        txtexamtime.setText("Enter Exam Time");
        txtexamtime.setBorder(null);
        txtexamtime.setOpaque(false);
        txtexamtime.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtexamtimeFocusGained(evt);
            }
        });
        txtexamtime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtexamtimeActionPerformed(evt);
            }
        });
        jPanel1.add(txtexamtime, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 240, 40));

        jlabel4.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jlabel4.setForeground(new java.awt.Color(51, 204, 0));
        jlabel4.setText("Exam Time");
        jPanel1.add(jlabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 240, 30));

        jlabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jlabel3.setForeground(new java.awt.Color(51, 204, 0));
        jlabel3.setText("Exam Date");
        jPanel1.add(jlabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 240, 30));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 240, -1));

        txtexamdate.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        txtexamdate.setForeground(new java.awt.Color(255, 255, 255));
        txtexamdate.setText("Enter Exam Date");
        txtexamdate.setBorder(null);
        txtexamdate.setOpaque(false);
        txtexamdate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtexamdateFocusGained(evt);
            }
        });
        jPanel1.add(txtexamdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 240, 40));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 240, -1));

        txtsubject.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        txtsubject.setForeground(new java.awt.Color(255, 255, 255));
        txtsubject.setText("Enter Course");
        txtsubject.setBorder(null);
        txtsubject.setOpaque(false);
        txtsubject.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtsubjectFocusGained(evt);
            }
        });
        txtsubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsubjectActionPerformed(evt);
            }
        });
        jPanel1.add(txtsubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 240, 40));

        jlabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jlabel2.setForeground(new java.awt.Color(51, 204, 0));
        jlabel2.setText("Course");
        jPanel1.add(jlabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 240, 30));

        txtexamid.setBackground(new java.awt.Color(204, 204, 204));
        txtexamid.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        txtexamid.setForeground(new java.awt.Color(255, 255, 255));
        txtexamid.setText("Enter Exam ID");
        txtexamid.setBorder(null);
        txtexamid.setOpaque(false);
        txtexamid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtexamidFocusGained(evt);
            }
        });
        jPanel1.add(txtexamid, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 240, 40));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 240, -1));

        jlabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jlabel1.setForeground(new java.awt.Color(51, 204, 0));
        jlabel1.setText("Exam ID");
        jPanel1.add(jlabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 240, 30));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\aksha\\Downloads\\iconfinder_book_285636.png")); // NOI18N
        jLabel3.setText("EXAMS");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 220, 90));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\aksha\\Desktop\\blue.jpg")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 830, 680));

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\aksha\\Desktop\\green.jpg")); // NOI18N
        jLabel1.setText("EXAMS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 110));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtexamtimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtexamtimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtexamtimeActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        String examid = txtexamid.getText();
        String courseid = txtsubject.getText();
        String examdate = txtexamdate.getText();
        String examtime = txtexamtime.getText();
        String semester= txtsemester.getSelectedItem().toString();
        String department= txtdepartment.getSelectedItem().toString();
      
         try {
             pst= conn.prepareStatement("insert into exam(examid,courseid,examdate,examtime,semester,department)values(?,?,?,?,?,?)");
             
             pst.setString(1,examid);
                pst.setString(2,courseid);
                pst.setString(3,examdate);
                pst.setString(4,examtime);
                pst.setString(5,semester);
                pst.setString(6,department);
                pst.executeUpdate();
                
                JOptionPane.showMessageDialog(null,"Examination details added");
                txtexamid.setText("");
                txtsubject.setText("");
                txtexamdate.setText("");
                txtexamtime.setText("");
                txtsemester.setSelectedIndex(-1);
                txtdepartment.setSelectedIndex(-1);
                
                txtexamid.requestFocus();
                
                
                
               
         } catch (SQLException ex) {
             Logger.getLogger(Exam.class.getName()).log(Level.SEVERE, null, ex);
         }
                
               
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtsubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsubjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsubjectActionPerformed

    private void txtexamidFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtexamidFocusGained
                  txtexamid.setText("");        
// TODO add your handling code here:
    }//GEN-LAST:event_txtexamidFocusGained

    private void txtsubjectFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtsubjectFocusGained
        // TODO add your handling code here:
        txtsubject.setText("");
    }//GEN-LAST:event_txtsubjectFocusGained

    private void txtexamdateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtexamdateFocusGained
        // TODO add your handling code here:
        txtexamdate.setText("");
    }//GEN-LAST:event_txtexamdateFocusGained

    private void txtexamtimeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtexamtimeFocusGained
        // TODO add your handling code here:
        txtexamtime.setText("");
    }//GEN-LAST:event_txtexamtimeFocusGained

    private void txtsemesterFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtsemesterFocusGained
        // TODO add your handling code here:
      
    }//GEN-LAST:event_txtsemesterFocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
        AdminDashboard ad= new AdminDashboard();
        ad.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable examtable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel jlabel1;
    private javax.swing.JLabel jlabel2;
    private javax.swing.JLabel jlabel3;
    private javax.swing.JLabel jlabel4;
    private javax.swing.JLabel jlcomboBox;
    private javax.swing.JLabel jlcomboBox1;
    private javax.swing.JComboBox<String> txtdepartment;
    private javax.swing.JTextField txtexamdate;
    private javax.swing.JTextField txtexamid;
    private javax.swing.JTextField txtexamtime;
    private javax.swing.JComboBox<String> txtsemester;
    private javax.swing.JTextField txtsubject;
    // End of variables declaration//GEN-END:variables
}
