/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentmanagement;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ishika Gupta
 */
public class student_course extends javax.swing.JFrame {
 Connection conn;
PreparedStatement pst;
ResultSet rs;
DefaultTableModel d;
    /**
     * Creates new form student_course
     */
    public student_course() {
        initComponents();
        connect();
        Course_Load();
        Dimension dim= Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2,dim.height/2-this.getSize().height/2);
        this.setBackground(new Color(0,0,0,0));
        jPanel1.setBackground(new Color(0,0,0,0));
        studentID.setBackground(new Color(0,0,0,0));
        CourseID.setBackground(new Color(0,0,0,0));
        CourseName.setBackground(new Color(0,0,0,0));
        CourseDuration.setBackground(new Color(0,0,0,0));
       
       
    }
    
    public void connect(){
     try {
         Class.forName("com.mysql.cj.jdbc.Driver");
         conn= DriverManager.getConnection("jdbc:mysql://localhost/schoolmanagementsystem","root","");
     } catch (ClassNotFoundException ex) {
         Logger.getLogger(student_course.class.getName()).log(Level.SEVERE, null, ex);
     } catch (SQLException ex) {
         Logger.getLogger(student_course.class.getName()).log(Level.SEVERE, null, ex);
     }
         
    }
    public void Course_Load(){
        
        int c;
       
     try {
         pst= conn.prepareStatement("select * from course");
         
              rs= pst.executeQuery();
     
        ResultSetMetaData rsd= rs.getMetaData();
        c= rsd.getColumnCount();
        
          d = (DefaultTableModel)coursetable.getModel();
        d.setRowCount(0);
        
        while(rs.next()){
            Vector v2= new Vector();
            for(int i=1;i<=c;i++){
                
                v2.add(rs.getString("courseid"));
                v2.add(rs.getString("coursename"));
                v2.add(rs.getString("courseduration"));
               
             
            }
            d.addRow(v2);
            
        }
     } catch (SQLException ex) {
         Logger.getLogger(attendance.class.getName()).log(Level.SEVERE, null, ex);
     }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        CourseDuration = new javax.swing.JTextField();
        jlabel4 = new javax.swing.JLabel();
        jlabel3 = new javax.swing.JLabel();
        CourseName = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jlabel2 = new javax.swing.JLabel();
        CourseID = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        coursetable = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        studentID = new javax.swing.JTextField();
        jlabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(255, 204, 204));
        jButton2.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Enroll");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 610, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 204, 204));
        jButton1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 610, -1, -1));

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 240, 30));

        CourseDuration.setBackground(new java.awt.Color(204, 204, 204));
        CourseDuration.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        CourseDuration.setForeground(new java.awt.Color(255, 255, 255));
        CourseDuration.setText("Enter Course Duration");
        CourseDuration.setBorder(null);
        CourseDuration.setOpaque(false);
        CourseDuration.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CourseDurationFocusGained(evt);
            }
        });
        CourseDuration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CourseDurationActionPerformed(evt);
            }
        });
        jPanel1.add(CourseDuration, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 240, 40));

        jlabel4.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jlabel4.setForeground(new java.awt.Color(255, 204, 204));
        jlabel4.setText("Course Duration");
        jPanel1.add(jlabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 280, 40));

        jlabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jlabel3.setForeground(new java.awt.Color(255, 204, 204));
        jlabel3.setText("Course Name");
        jPanel1.add(jlabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 280, 40));

        CourseName.setBackground(new java.awt.Color(204, 204, 204));
        CourseName.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        CourseName.setForeground(new java.awt.Color(255, 255, 255));
        CourseName.setText("Enter Course Name");
        CourseName.setBorder(null);
        CourseName.setOpaque(false);
        CourseName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CourseNameFocusGained(evt);
            }
        });
        CourseName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CourseNameActionPerformed(evt);
            }
        });
        jPanel1.add(CourseName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 240, 40));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 240, 30));

        jlabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jlabel2.setForeground(new java.awt.Color(255, 204, 204));
        jlabel2.setText("Course ID");
        jPanel1.add(jlabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 280, 40));

        CourseID.setBackground(new java.awt.Color(204, 204, 204));
        CourseID.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        CourseID.setForeground(new java.awt.Color(255, 255, 255));
        CourseID.setText("Enter Course ID");
        CourseID.setBorder(null);
        CourseID.setOpaque(false);
        CourseID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CourseIDFocusGained(evt);
            }
        });
        CourseID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CourseIDActionPerformed(evt);
            }
        });
        jPanel1.add(CourseID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 240, 40));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 240, 30));

        coursetable.setBackground(new java.awt.Color(255, 204, 255));
        coursetable.setForeground(new java.awt.Color(51, 51, 51));
        coursetable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Course ID", "Course Name", "Course Duration"
            }
        ));
        jScrollPane1.setViewportView(coursetable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, 490, 320));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 240, 30));

        studentID.setBackground(new java.awt.Color(204, 204, 204));
        studentID.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        studentID.setForeground(new java.awt.Color(255, 255, 255));
        studentID.setText("Enter Student ID");
        studentID.setBorder(null);
        studentID.setOpaque(false);
        studentID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                studentIDFocusGained(evt);
            }
        });
        studentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentIDActionPerformed(evt);
            }
        });
        jPanel1.add(studentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 240, 40));

        jlabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jlabel1.setForeground(new java.awt.Color(255, 204, 204));
        jlabel1.setText("Student ID");
        jPanel1.add(jlabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 280, 40));

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\aksha\\Downloads\\iconfinder_LIBRARY_2_753918.png")); // NOI18N
        jLabel3.setText(" COURSE");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 270, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\aksha\\Desktop\\pink.jpg")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 120));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 110));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\aksha\\Desktop\\blue.jpg")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 1010, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studentIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_studentIDFocusGained
        studentID.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_studentIDFocusGained

    private void studentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentIDActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_studentIDActionPerformed

    private void CourseIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CourseIDFocusGained
        // TODO add your handling code here:
        CourseID.setText("");
    }//GEN-LAST:event_CourseIDFocusGained

    private void CourseIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CourseIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CourseIDActionPerformed

    private void CourseNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CourseNameFocusGained
        CourseName.setText("");
// TODO add your handling code here:
    }//GEN-LAST:event_CourseNameFocusGained

    private void CourseNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CourseNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CourseNameActionPerformed

    private void CourseDurationFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CourseDurationFocusGained
        CourseDuration.setText("");
// TODO add your handling code here:
    }//GEN-LAST:event_CourseDurationFocusGained

    private void CourseDurationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CourseDurationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CourseDurationActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
        StudentHomePage ad= new StudentHomePage();
        ad.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
         String studentid = studentID.getText();
        String courseid = CourseID.getText();
        String coursename = CourseName.getText();
        String duration = CourseDuration.getText();
        
     try {
         pst= conn.prepareStatement("insert into course_student (studentid,courseid,coursename,duration)values(?,?,?,?)");
         pst.setString(1,studentid);
                pst.setString(2,courseid);
                pst.setString(3,coursename);
                pst.setString(4,duration);
                
                pst.executeUpdate();
                
                JOptionPane.showMessageDialog(null,"Enrolled in the Course");
                 studentID.setText("");
                CourseID.setText("");
                CourseName.setText("");
               
                CourseDuration.setText("");
                
               
                studentID.requestFocus();
     } catch (SQLException ex) {
         Logger.getLogger(student_course.class.getName()).log(Level.SEVERE, null, ex);
     }
         
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(student_course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(student_course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(student_course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(student_course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new student_course().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CourseDuration;
    private javax.swing.JTextField CourseID;
    private javax.swing.JTextField CourseName;
    private javax.swing.JTable coursetable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel jlabel1;
    private javax.swing.JLabel jlabel2;
    private javax.swing.JLabel jlabel3;
    private javax.swing.JLabel jlabel4;
    private javax.swing.JTextField studentID;
    // End of variables declaration//GEN-END:variables
}
