/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentmanagement;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ishika Gupta
 */
public class Student extends javax.swing.JFrame {
 Connection conn;
PreparedStatement pst;
ResultSet rs;

    /**
     * Creates new form Student
     */
    public Student() {
        initComponents();
        connect();
        
        Dimension dim= Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2,dim.height/2-this.getSize().height/2);
        this.setBackground(new Color(0,0,0,0));
        jPanel1.setBackground(new Color(0,0,0,0));
        txtstu.setBackground(new Color(0,0,0,0));
        txtstuname.setBackground(new Color(0,0,0,0));
        txtfname.setBackground(new Color(0,0,0,0));
        txtcity.setBackground(new Color(0,0,0,0));
        txtemail.setBackground(new Color(0,0,0,0));   
        txtphone.setBackground(new Color(0,0,0,0));
        txtdob.setBackground(new Color(0,0,0,0));
        txtadd.setBackground(new Color(0,0,0,0));
    }
    public void connect(){
     try {
         Class.forName("com.mysql.cj.jdbc.Driver");
          conn= DriverManager.getConnection("jdbc:mysql://localhost/schoolmanagementsystem","root","");
          
          
          
     } catch (ClassNotFoundException ex) {
         Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, ex);
     } catch (SQLException ex) {
         Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, ex);
     }
             
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JSeparator();
        txtadd = new javax.swing.JTextField();
        jlabel8 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        txtphone = new javax.swing.JTextField();
        jlabel7 = new javax.swing.JLabel();
        jlabel6 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        txtcity = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        txtfname = new javax.swing.JTextField();
        jlabel5 = new javax.swing.JLabel();
        jlabel4 = new javax.swing.JLabel();
        txtdob = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jlabel3 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jlabel2 = new javax.swing.JLabel();
        txtstuname = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        txtstu = new javax.swing.JTextField();
        jlabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setBackground(new java.awt.Color(51, 240, 0));
        jButton3.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Add");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 550, -1, -1));

        jButton1.setBackground(new java.awt.Color(51, 240, 0));
        jButton1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 550, -1, -1));

        jSeparator8.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 500, 240, 20));

        txtadd.setBackground(new java.awt.Color(204, 204, 204));
        txtadd.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        txtadd.setForeground(new java.awt.Color(255, 255, 255));
        txtadd.setText("Enter address");
        txtadd.setBorder(null);
        txtadd.setOpaque(false);
        txtadd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtaddFocusGained(evt);
            }
        });
        txtadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaddActionPerformed(evt);
            }
        });
        jPanel1.add(txtadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 460, 240, 40));

        jlabel8.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jlabel8.setForeground(new java.awt.Color(51, 204, 0));
        jlabel8.setText("Address");
        jPanel1.add(jlabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 430, 240, 30));

        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 410, 240, 20));

        txtphone.setBackground(new java.awt.Color(204, 204, 204));
        txtphone.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        txtphone.setForeground(new java.awt.Color(255, 255, 255));
        txtphone.setText("Enter Phone No.");
        txtphone.setBorder(null);
        txtphone.setOpaque(false);
        txtphone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtphoneFocusGained(evt);
            }
        });
        txtphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtphoneActionPerformed(evt);
            }
        });
        jPanel1.add(txtphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, 240, 40));

        jlabel7.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jlabel7.setForeground(new java.awt.Color(51, 204, 0));
        jlabel7.setText("Phone No.");
        jPanel1.add(jlabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, 240, 30));

        jlabel6.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jlabel6.setForeground(new java.awt.Color(51, 204, 0));
        jlabel6.setText("City");
        jPanel1.add(jlabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 240, 30));

        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, 240, -1));

        txtcity.setBackground(new java.awt.Color(204, 204, 204));
        txtcity.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        txtcity.setForeground(new java.awt.Color(255, 255, 255));
        txtcity.setText("Enter City");
        txtcity.setBorder(null);
        txtcity.setOpaque(false);
        txtcity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtcityFocusGained(evt);
            }
        });
        txtcity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcityActionPerformed(evt);
            }
        });
        jPanel1.add(txtcity, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 240, 40));

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 240, -1));

        txtfname.setBackground(new java.awt.Color(204, 204, 204));
        txtfname.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        txtfname.setForeground(new java.awt.Color(255, 255, 255));
        txtfname.setText("Enter Father's Name");
        txtfname.setBorder(null);
        txtfname.setOpaque(false);
        txtfname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtfnameFocusGained(evt);
            }
        });
        txtfname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfnameActionPerformed(evt);
            }
        });
        jPanel1.add(txtfname, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 240, 40));

        jlabel5.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jlabel5.setForeground(new java.awt.Color(51, 204, 0));
        jlabel5.setText("Father's Name");
        jPanel1.add(jlabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 240, 30));

        jlabel4.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jlabel4.setForeground(new java.awt.Color(51, 204, 0));
        jlabel4.setText("Date Of Birth");
        jPanel1.add(jlabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 240, 30));

        txtdob.setBackground(new java.awt.Color(204, 204, 204));
        txtdob.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        txtdob.setForeground(new java.awt.Color(255, 255, 255));
        txtdob.setText("Enter D.O.B");
        txtdob.setBorder(null);
        txtdob.setOpaque(false);
        txtdob.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtdobFocusGained(evt);
            }
        });
        txtdob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdobActionPerformed(evt);
            }
        });
        jPanel1.add(txtdob, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 240, 40));

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 240, 10));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 240, 10));

        jlabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jlabel3.setForeground(new java.awt.Color(51, 204, 0));
        jlabel3.setText("E-mail");
        jPanel1.add(jlabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 240, 30));

        txtemail.setBackground(new java.awt.Color(204, 204, 204));
        txtemail.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        txtemail.setForeground(new java.awt.Color(255, 255, 255));
        txtemail.setText("Enter email");
        txtemail.setBorder(null);
        txtemail.setOpaque(false);
        txtemail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtemailFocusGained(evt);
            }
        });
        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });
        jPanel1.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 240, 40));

        jlabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jlabel2.setForeground(new java.awt.Color(51, 204, 0));
        jlabel2.setText("Student Name");
        jPanel1.add(jlabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 240, 30));

        txtstuname.setBackground(new java.awt.Color(204, 204, 204));
        txtstuname.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        txtstuname.setForeground(new java.awt.Color(255, 255, 255));
        txtstuname.setText("Enter Student Name");
        txtstuname.setBorder(null);
        txtstuname.setOpaque(false);
        txtstuname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtstunameFocusGained(evt);
            }
        });
        txtstuname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstunameActionPerformed(evt);
            }
        });
        jPanel1.add(txtstuname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 240, 40));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 240, 10));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 240, -1));

        txtstu.setBackground(new java.awt.Color(204, 204, 204));
        txtstu.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        txtstu.setForeground(new java.awt.Color(255, 255, 255));
        txtstu.setText("Enter Student ID");
        txtstu.setBorder(null);
        txtstu.setOpaque(false);
        txtstu.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtstuFocusGained(evt);
            }
        });
        txtstu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstuActionPerformed(evt);
            }
        });
        jPanel1.add(txtstu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 240, 40));

        jlabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jlabel1.setForeground(new java.awt.Color(51, 204, 0));
        jlabel1.setText("Student ID");
        jPanel1.add(jlabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 240, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\aksha\\Desktop\\blue.jpg")); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 650, 500));

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\aksha\\Downloads\\iconfinder_ID-card-avatar-student-education-school-library_5269082.png")); // NOI18N
        jLabel2.setText("STUDENT");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 320, 90));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\aksha\\Desktop\\green.jpg")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 100));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtstuFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtstuFocusGained
        txtstu.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstuFocusGained

    private void txtstuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstuActionPerformed

    private void txtstunameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtstunameFocusGained
       txtstuname.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstunameFocusGained

    private void txtstunameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstunameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstunameActionPerformed

    private void txtemailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtemailFocusGained
              txtemail.setText("");       // TODO add your handling code here:
    }//GEN-LAST:event_txtemailFocusGained

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void txtdobFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtdobFocusGained
        txtdob.setText("");
// TODO add your handling code here:
    }//GEN-LAST:event_txtdobFocusGained

    private void txtdobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdobActionPerformed

    private void txtfnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtfnameFocusGained
        txtfname.setText("");
// TODO add your handling code here:
    }//GEN-LAST:event_txtfnameFocusGained

    private void txtfnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfnameActionPerformed

    private void txtcityFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtcityFocusGained
        txtcity.setText("");
// TODO add your handling code here:
    }//GEN-LAST:event_txtcityFocusGained

    private void txtcityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcityActionPerformed

    private void txtphoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtphoneFocusGained
        txtphone.setText("");
// TODO add your handling code here:
    }//GEN-LAST:event_txtphoneFocusGained

    private void txtphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtphoneActionPerformed

    private void txtaddFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtaddFocusGained
       txtadd.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaddFocusGained

    private void txtaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaddActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String studentid = txtstu.getText();
        String name = txtstuname.getText();
        String fathername = txtfname.getText();
        String city = txtcity.getText();
        String email = txtemail.getText();
        String phone = txtphone.getText();
        String dateofbirth = txtdob.getText();
        String address = txtadd.getText();
        
     try {
         pst= conn.prepareStatement("insert into student(studentid,name,fathername,city,email,phone,dateofbirth,address)values(?,?,?,?,?,?,?,?)");
          pst.setString(1,studentid);
                pst.setString(2,name);
                pst.setString(3,fathername);
                pst.setString(4,city);
                pst.setString(5,email);
                pst.setString(6,phone);
                pst.setString(7,dateofbirth);
                pst.setString(8,address);
                pst.executeUpdate();
                
                JOptionPane.showMessageDialog(null,"New Student added");
                txtstu.setText("");
                txtstuname.setText("");
                txtfname.setText("");
                txtcity.setText("");
                txtemail.setText("");
                txtphone.setText("");
                txtdob.setText("");
                txtadd.setText("");
               
                txtstu.requestFocus();
                
     } catch (SQLException ex) {
         Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, ex);
     }
                
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
        AdminDashboard ad= new AdminDashboard();
        ad.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel jlabel1;
    private javax.swing.JLabel jlabel2;
    private javax.swing.JLabel jlabel3;
    private javax.swing.JLabel jlabel4;
    private javax.swing.JLabel jlabel5;
    private javax.swing.JLabel jlabel6;
    private javax.swing.JLabel jlabel7;
    private javax.swing.JLabel jlabel8;
    private javax.swing.JTextField txtadd;
    private javax.swing.JTextField txtcity;
    private javax.swing.JTextField txtdob;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtphone;
    private javax.swing.JTextField txtstu;
    private javax.swing.JTextField txtstuname;
    // End of variables declaration//GEN-END:variables
}
